// This file is auto-generated by @hey-api/openapi-ts

import type { RepoChangeFilesResponse } from './types.gen';

const commitMetaSchemaResponseTransformer = (data: any) => {
  if (data.created) {
    data.created = new Date(data.created);
  }
  return data;
};

const fileCommitResponseSchemaResponseTransformer = (data: any) => {
  if (data.created) {
    data.created = new Date(data.created);
  }
  if (data.parents) {
    data.parents = data.parents.map((item: any) =>
      commitMetaSchemaResponseTransformer(item)
    );
  }
  if (data.tree) {
    data.tree = commitMetaSchemaResponseTransformer(data.tree);
  }
  return data;
};

const contentsResponseSchemaResponseTransformer = (data: any) => {
  if (data.last_commit_when) {
    data.last_commit_when = new Date(data.last_commit_when);
  }
  return data;
};

const filesResponseSchemaResponseTransformer = (data: any) => {
  if (data.commit) {
    data.commit = fileCommitResponseSchemaResponseTransformer(data.commit);
  }
  if (data.files) {
    data.files = data.files.map((item: any) =>
      contentsResponseSchemaResponseTransformer(item)
    );
  }
  return data;
};

export const repoChangeFilesResponseTransformer = async (
  data: any
): Promise<RepoChangeFilesResponse> => {
  data = filesResponseSchemaResponseTransformer(data);
  return data;
};
