// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl:
    | `https://${string}/api/v1`
    | `http://${string}/api/v1`
    | (string & {});
};

/**
 * APIError is an api error with a message
 */
export type ApiError = {
  message?: string;
  url?: string;
};

export type ApiNotFound = {
  errors?: Array<string>;
  message?: string;
  url?: string;
};

export type ApiRepoArchivedError = {
  message?: string;
  url?: string;
};

/**
 * ChangeFileOperation for creating, updating or deleting a file
 */
export type ChangeFileOperation = {
  /**
   * new or updated file content, must be base64 encoded
   */
  content?: string;
  /**
   * old path of the file to move
   */
  from_path?: string;
  /**
   * indicates what to do with the file
   */
  operation: 'create' | 'update' | 'delete';
  /**
   * path to the existing or new file
   */
  path: string;
  /**
   * sha is the SHA for the file that already exists, required for update or delete
   */
  sha?: string;
};

/**
 * ChangeFilesOptions options for creating, updating or deleting multiple files
 * Note: `author` and `committer` are optional (if only one is given, it will be used for the other, otherwise the authenticated user will be used)
 */
export type ChangeFilesOptions = {
  author?: Identity;
  /**
   * branch (optional) to base this file from. if not given, the default branch is used
   */
  branch?: string;
  committer?: Identity;
  dates?: CommitDateOptions;
  /**
   * list of file operations
   */
  files: Array<ChangeFileOperation>;
  /**
   * message (optional) for the commit of this file. if not supplied, a default message will be used
   */
  message?: string;
  /**
   * new_branch (optional) will make a new branch from `branch` before creating the file
   */
  new_branch?: string;
  /**
   * Add a Signed-off-by trailer by the committer at the end of the commit log message.
   */
  signoff?: boolean;
};

/**
 * CommitDateOptions store dates for GIT_AUTHOR_DATE and GIT_COMMITTER_DATE
 */
export type CommitDateOptions = {
  author?: Date;
  committer?: Date;
};

/**
 * CommitMeta contains meta information of a commit in terms of API.
 */
export type CommitMeta = {
  created?: Date;
  sha?: string;
  url?: string;
};

/**
 * CommitUser contains information of a user in the context of a commit.
 */
export type CommitUser = {
  date?: string;
  email?: string;
  name?: string;
};

/**
 * ContentsResponse contains information about a repo's entry's (dir, file, symlink, submodule) metadata and content
 */
export type ContentsResponse = {
  _links?: FileLinksResponse;
  /**
   * `content` is populated when `type` is `file`, otherwise null
   */
  content?: string;
  download_url?: string;
  /**
   * `encoding` is populated when `type` is `file`, otherwise null
   */
  encoding?: string;
  git_url?: string;
  html_url?: string;
  last_commit_sha?: string;
  last_commit_when?: Date;
  name?: string;
  path?: string;
  sha?: string;
  size?: number;
  /**
   * `submodule_git_url` is populated when `type` is `submodule`, otherwise null
   */
  submodule_git_url?: string;
  /**
   * `target` is populated when `type` is `symlink`, otherwise null
   */
  target?: string;
  /**
   * `type` will be `file`, `dir`, `symlink`, or `submodule`
   */
  type?: string;
  url?: string;
};

/**
 * FileCommitResponse contains information generated from a Git commit for a repo's file.
 */
export type FileCommitResponse = {
  author?: CommitUser;
  committer?: CommitUser;
  created?: Date;
  html_url?: string;
  message?: string;
  parents?: Array<CommitMeta>;
  sha?: string;
  tree?: CommitMeta;
  url?: string;
};

/**
 * FileLinksResponse contains the links for a repo's file
 */
export type FileLinksResponse = {
  git?: string;
  html?: string;
  self?: string;
};

/**
 * FilesResponse contains information about multiple files from a repo
 */
export type FilesResponse = {
  commit?: FileCommitResponse;
  files?: Array<ContentsResponse>;
  verification?: PayloadCommitVerification;
};

/**
 * Identity for a person's identity like an author or committer
 */
export type Identity = {
  email?: string;
  name?: string;
};

/**
 * PayloadCommitVerification represents the GPG verification of a commit
 */
export type PayloadCommitVerification = {
  payload?: string;
  reason?: string;
  signature?: string;
  signer?: PayloadUser;
  verified?: boolean;
};

/**
 * PayloadUser represents the author or committer of a commit
 */
export type PayloadUser = {
  email?: string;
  /**
   * Full name of the commit author
   */
  name?: string;
  username?: string;
};

export type RepoChangeFilesData = {
  body: ChangeFilesOptions;
  path: {
    /**
     * owner of the repo
     */
    owner: string;
    /**
     * name of the repo
     */
    repo: string;
  };
  query?: never;
  url: '/repos/{owner}/{repo}/contents';
};

export type RepoChangeFilesErrors = {
  /**
   * APIError is error format response
   */
  403: ApiError;
  /**
   * APINotFound is a not found error response
   */
  404: ApiNotFound;
  /**
   * APIConflict is a conflict empty response
   */
  409: unknown;
  /**
   * QuotaExceeded
   */
  413: unknown;
  /**
   * APIError is error format response
   */
  422: ApiError;
  /**
   * APIRepoArchivedError is an error that is raised when an archived repo should be modified
   */
  423: ApiRepoArchivedError;
};

export type RepoChangeFilesError =
  RepoChangeFilesErrors[keyof RepoChangeFilesErrors];

export type RepoChangeFilesResponses = {
  /**
   * FilesResponse
   */
  201: FilesResponse;
};

export type RepoChangeFilesResponse =
  RepoChangeFilesResponses[keyof RepoChangeFilesResponses];
